#########################
## Sample Sass Lint File
#########################
# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: true
  # Set the formatter to 'html'
  formatter: html
  # Output file instead of logging results
  output-file: 'linters/sass-lint.html'
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  include: 'lib/**/*.s+(a|c)ss'
  ignore:
    - 'sass/vendor/**/*.*'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  class-name-format:     
    - 1
    - 
      convention: hyphenatedbem
      
  placeholder-name-format:
    - 1
    - 
      convention: hyphenatedbem

  placeholder-in-extend: 2
  no-trailing-whitespace: 0
  no-color-keywords: 0
  no-color-literals: 0
  mixins-before-declarations: 
    - 2
    -
      exclude:
        - breakpoint

  no-warn: 0
  no-debug: 1
  no-ids: 2
  no-important: 2
  indentation:
    - 1
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - content
        - display
        - position
        - 
      ignore-custom-properties: true
  space-before-colon: 1 
  space-after-colon: 1    
  variable-for-property:
    - 2
    -
      properties:
        - 